controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

meeting_details:
    path: /meeting/details
    controller: App\Controller\MeetingController::meetingDetails

view_opportunities:
  path: /view
  controller: App\Controller\OpportunityController::viewOpportunities


